
# Sets the website to use local javascript/css only.  All resource files
# will be local if this variable is set to "yes"; otherwise internet 
# access is required for any other string.
#local: "true"
local: "false"


